INFO flwr 2024-01-18 11:20:34,692 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-18 11:20:34,827 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-18 11:20:34,827 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-18 11:20:34,828 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2024-01-18 11:21:55,171 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2024-01-18 11:21:55,188 | server.py:277 | Received initial parameters from one random client
INFO flwr 2024-01-18 11:21:55,189 | server.py:88 | Evaluating initial parameters
DEBUG flwr 2024-01-18 11:21:55,174 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:55,174 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:55,183 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:55,191 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:55,193 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:55,194 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:55,203 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:55,211 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:55,214 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:55,214 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:55,223 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:55,255 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:55,259 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:55,259 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2024-01-18 11:21:55,260 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:55,263 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:55,263 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-18 11:21:55,263 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:55,267 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:55,276 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:55,279 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:55,279 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:55,283 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:55,290 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:55,293 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:55,294 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:55,298 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:55,319 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:55,322 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:55,322 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:55,330 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:55,338 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:55,341 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:55,341 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:55,345 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:55,385 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:55,387 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:55,387 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:55,391 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:57,150 | server.py:91 | initial parameters (loss, other metrics): 2.3028675574271174, {'accuracy': 0.1033}
INFO flwr 2024-01-18 11:21:57,151 | server.py:101 | FL starting
DEBUG flwr 2024-01-18 11:23:58,504 | server.py:218 | fit_round 1: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-01-18 11:24:11,064 | server.py:232 | fit_round 1 received 10 results and 0 failures
WARNING flwr 2024-01-18 11:24:11,118 | fedmedian.py:156 | No fit_metrics_aggregation_fn provided
INFO flwr 2024-01-18 11:24:13,117 | server.py:119 | fit progress: (1, 2.284183907108332, {'accuracy': 0.1681}, 135.96629853360355)
INFO flwr 2024-01-18 11:24:13,117 | server.py:166 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2024-01-18 11:24:13,118 | server.py:218 | fit_round 2: strategy sampled 19 clients (out of 19)
DEBUG flwr 2024-01-18 11:24:23,657 | server.py:232 | fit_round 2 received 19 results and 0 failures
INFO flwr 2024-01-18 11:24:25,697 | server.py:119 | fit progress: (2, 2.2725389967389726, {'accuracy': 0.2111}, 148.54592421464622)
INFO flwr 2024-01-18 11:24:25,697 | server.py:166 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2024-01-18 11:26:40,695 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:40,695 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:40,899 | connection.py:113 | gRPC channel closed
booting up client 6
DEBUG flwr 2024-01-18 11:26:40,899 | connection.py:113 | gRPC channel closed
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
booting up client 2
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {grpc_message:"Socket closed", grpc_status:14, created_time:"2024-01-18T11:26:40.69318738+01:00"}"
>
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2024-01-18T11:26:40.693187571+01:00", grpc_status:14, grpc_message:"Socket closed"}"
>
DEBUG flwr 2024-01-18 11:26:41,723 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:41,723 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:41,723 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:41,724 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:41,927 | connection.py:113 | gRPC channel closed
booting up client 3
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
DEBUG flwr 2024-01-18 11:26:41,927 | connection.py:113 | gRPC channel closed
booting up client 8
DEBUG flwr 2024-01-18 11:26:41,928 | connection.py:113 | gRPC channel closed
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
booting up client 5
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
DEBUG flwr 2024-01-18 11:26:41,928 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
srun: error: influ4: task 2: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9232960.1
slurmstepd: error: *** STEP 9232960.1 ON influ4 CANCELLED AT 2024-01-18T11:26:41 ***
srun: error: influ4: tasks 0-1,3-9: Terminated
srun: Force Terminated StepId=9232960.1
