INFO flwr 2024-01-17 15:24:09,075 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-17 15:24:09,224 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-17 15:24:09,225 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-17 15:24:09,225 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2024-01-17 15:24:56,123 | server.py:277 | Received initial parameters from one random client
INFO flwr 2024-01-17 15:24:56,125 | server.py:88 | Evaluating initial parameters
INFO flwr 2024-01-17 15:24:57,099 | server.py:91 | initial parameters (loss, other metrics): 2.3079591019314463, {'accuracy': 0.1043}
INFO flwr 2024-01-17 15:24:57,099 | server.py:101 | FL starting
INFO flwr 2024-01-17 15:25:13,579 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:13,581 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:13,581 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:13,584 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:13,611 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:13,612 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:13,613 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:13,616 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:13,655 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:13,657 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:13,657 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:13,660 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:13,667 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:13,669 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:13,669 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:13,672 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:13,697 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2024-01-17 15:25:13,699 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:13,700 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:13,701 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:13,701 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:13,701 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:13,704 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:25:13,705 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:13,708 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:13,710 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:13,711 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:13,714 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:13,721 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:13,725 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:13,725 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:13,728 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:13,738 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2024-01-17 15:25:13,738 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:13,739 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:13,739 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:13,740 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:13,740 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:13,743 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:25:13,743 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:29:42,011 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:29:42,013 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:29:42,024 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:29:43,474 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:29:43,634 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Socket closed", grpc_status:14, created_time:"2024-01-17T15:29:43.632797898+01:00"}"
>
DEBUG flwr 2024-01-17 15:29:43,677 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2024-01-17T15:29:43.473337057+01:00", grpc_status:14, grpc_message:"Socket closed"}"
>
DEBUG flwr 2024-01-17 15:29:43,747 | connection.py:39 | ChannelConnectivity.IDLE
booting up client 0
DEBUG flwr 2024-01-17 15:29:43,950 | connection.py:113 | gRPC channel closed
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"ping timeout", grpc_status:14, created_time:"2024-01-17T15:29:43.746039014+01:00"}"
>
srun: error: gpu05: tasks 0,3: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9231385.1
slurmstepd: error: *** STEP 9231385.1 ON gpu05 CANCELLED AT 2024-01-17T15:29:44 ***
srun: error: gpu05: tasks 1-2,4-9: Terminated
srun: Force Terminated StepId=9231385.1
