INFO flwr 2024-01-18 11:20:34,684 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-18 11:20:34,813 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-18 11:20:34,813 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-18 11:20:34,813 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2024-01-18 11:21:22,823 | server.py:277 | Received initial parameters from one random client
INFO flwr 2024-01-18 11:21:22,823 | server.py:88 | Evaluating initial parameters
INFO flwr 2024-01-18 11:21:22,837 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:22,839 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:22,839 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:22,842 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,406 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:23,407 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,407 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,411 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,592 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2024-01-18 11:21:23,592 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:23,593 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,594 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,594 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,594 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,597 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-18 11:21:23,597 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,613 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:23,614 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,614 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,617 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,726 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:23,728 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,729 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,732 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,779 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:23,781 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,781 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,785 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,797 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:23,798 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,798 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,801 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,835 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:23,838 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,838 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,842 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,857 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:21:23,859 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:21:23,859 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:21:23,863 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:21:23,984 | server.py:91 | initial parameters (loss, other metrics): 2.307999235053295, {'accuracy': 0.1241}
INFO flwr 2024-01-18 11:21:23,984 | server.py:101 | FL starting
DEBUG flwr 2024-01-18 12:07:10,055 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-18 12:07:10,055 | app.py:185 | Disconnect and shut down
booting up client 5
DEBUG flwr 2024-01-18 12:07:10,056 | connection.py:113 | gRPC channel closed
DEBUG flwr 2024-01-18 12:07:10,056 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-18 12:07:10,056 | app.py:185 | Disconnect and shut down
INFO flwr 2024-01-18 12:07:10,056 | app.py:185 | Disconnect and shut down
booting up client 7
booting up client 0
DEBUG flwr 2024-01-18 12:12:32,566 | connection.py:113 | gRPC channel closed
DEBUG flwr 2024-01-18 12:12:32,566 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-18 12:12:32,566 | app.py:185 | Disconnect and shut down
DEBUG flwr 2024-01-18 12:12:32,566 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-18 12:12:32,566 | app.py:185 | Disconnect and shut down
DEBUG flwr 2024-01-18 12:12:32,566 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-18 12:12:32,566 | app.py:185 | Disconnect and shut down
booting up client 4
INFO flwr 2024-01-18 12:12:32,566 | app.py:185 | Disconnect and shut down
booting up client 1
booting up client 6
booting up client 2
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
DEBUG flwr 2024-01-18 15:20:38,828 | connection.py:113 | gRPC channel closed
DEBUG flwr 2024-01-18 15:20:38,828 | connection.py:113 | gRPC channel closed
booting up client 8
booting up client 9
Traceback (most recent call last):
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 9232955.0 ON 3dgi1 CANCELLED AT 2024-01-18T15:20:38 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 9232955 ON 3dgi1 CANCELLED AT 2024-01-18T15:20:38 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 9232955.1 ON 3dgi1 CANCELLED AT 2024-01-18T15:20:38 DUE TO TIME LIMIT ***
