log_nc10_nro400_str1_lr0.0001_rho0.5_dsetMNIST_10c_iid1_ed0.txt
INFO flwr 2024-01-31 09:58:17,513 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-31 09:58:17,589 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-31 09:58:17,589 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-31 09:58:17,589 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2024-01-31 09:59:01,184 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2024-01-31 09:59:01,194 | server.py:277 | Received initial parameters from one random client
INFO flwr 2024-01-31 09:59:01,195 | server.py:88 | Evaluating initial parameters
DEBUG flwr 2024-01-31 09:59:01,185 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 09:59:01,185 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-31 09:59:01,189 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-31 09:59:01,599 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-31 09:59:01,601 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 09:59:01,601 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-31 09:59:01,604 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-31 09:59:02,353 | server.py:91 | initial parameters (loss, other metrics): 2.307069842550778, {'accuracy': 0.0874}
INFO flwr 2024-01-31 09:59:02,353 | server.py:101 | FL starting
INFO flwr 2024-01-31 09:59:02,652 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-31 09:59:02,654 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 09:59:02,654 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-31 09:59:02,658 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-31 09:59:02,835 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-31 09:59:02,837 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 09:59:02,837 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-31 09:59:02,841 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-31 09:59:02,873 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-31 09:59:02,874 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 09:59:02,874 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-31 09:59:02,877 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-31 09:59:02,984 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-31 09:59:03,012 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 09:59:03,012 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-31 09:59:03,015 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-31 09:59:03,252 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-31 09:59:03,254 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 09:59:03,254 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-31 09:59:03,257 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-31 09:59:03,491 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-31 09:59:03,495 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 09:59:03,495 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-31 09:59:03,499 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-31 09:59:03,868 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-31 09:59:03,871 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 09:59:03,872 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-31 09:59:03,875 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-31 09:59:04,045 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-31 09:59:04,065 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 09:59:04,065 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-31 09:59:04,069 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-31 13:56:51,933 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-31 13:56:51,935 | connection.py:113 | gRPC channel closed
booting up client 6
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
DEBUG flwr 2024-01-31 13:56:51,935 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    client = ADMM_FlowerClient(X_train, y_train, args.lr, args.rho, args.dset)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    client = ADMM_FlowerClient(X_train, y_train, args.lr, args.rho, args.dset)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {grpc_message:"Socket closed", grpc_status:14, created_time:"2024-01-31T13:56:51.932019848+01:00"}"
>
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-01-31T13:56:51.933541514+01:00", grpc_status:14, grpc_message:"Socket closed"}"
>
DEBUG flwr 2024-01-31 13:56:52,136 | connection.py:113 | gRPC channel closed
booting up client 2
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    client = ADMM_FlowerClient(X_train, y_train, args.lr, args.rho, args.dset)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {grpc_message:"Socket closed", grpc_status:14, created_time:"2024-01-31T13:56:51.93204659+01:00"}"
>
srun: error: 3dgi1: tasks 0,2,6: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9271548.1
slurmstepd: error: *** STEP 9271548.1 ON 3dgi1 CANCELLED AT 2024-01-31T13:56:52 ***
slurmstepd: error: common_file_write_content: unable to open '/sys/fs/cgroup/freezer/slurm/uid_618619/job_9271548/step_1/freezer.state' for writing: Permission denied
srun: error: 3dgi1: tasks 1,3-5,7-9: Terminated
srun: Force Terminated StepId=9271548.1
