INFO flwr 2023-12-19 16:46:53,920 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2023-12-19 16:46:53,970 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2023-12-19 16:46:53,971 | server.py:86 | Initializing global parameters
INFO flwr 2023-12-19 16:46:53,972 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2023-12-19 16:47:28,309 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2023-12-19 16:47:28,318 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-12-19 16:47:28,319 | server.py:88 | Evaluating initial parameters
DEBUG flwr 2023-12-19 16:47:28,311 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 16:47:28,312 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 16:47:28,315 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 16:47:29,251 | server.py:91 | initial parameters (loss, other metrics): 2.3063021857976915, {'accuracy': 0.1214}
INFO flwr 2023-12-19 16:47:29,251 | server.py:101 | FL starting
INFO flwr 2023-12-19 16:47:32,243 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 16:47:32,246 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 16:47:32,246 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 16:47:32,249 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 16:47:33,404 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 16:47:33,406 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 16:47:33,407 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 16:47:33,410 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 16:47:33,580 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 16:47:33,583 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 16:47:33,583 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 16:47:33,587 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 16:47:33,591 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 16:47:33,595 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 16:47:33,595 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 16:47:33,598 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 16:47:33,627 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 16:47:33,629 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 16:47:33,629 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 16:47:33,633 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 16:47:33,698 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 16:47:33,699 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 16:47:33,700 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 16:47:33,704 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 16:47:33,704 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 16:47:33,707 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 16:47:33,707 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 16:47:33,711 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2023-12-19 16:47:33,861 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2023-12-19 16:47:33,862 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-12-19 16:47:33,863 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 16:47:33,864 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 16:47:33,864 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 16:47:33,865 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-12-19 16:47:33,869 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-19 16:47:33,869 | server.py:218 | fit_round 1: strategy sampled 10 clients (out of 10)
DEBUG flwr 2023-12-19 16:47:33,869 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-12-19 16:47:37,682 | server.py:232 | fit_round 1 received 10 results and 0 failures
server strategy: ADMM
number of clients: 10
round:      0
Server-side evaluation loss 2.3063021857976915 / accuracy 0.1214
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_server.py", line 151, in <module>
    fl.server.start_server(config=fl.server.ServerConfig(num_rounds=NUM_ROUNDS), strategy=strat)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/server/app.py", line 176, in start_server
    hist = _fl(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/server/app.py", line 217, in _fl
    hist = server.fit(num_rounds=config.num_rounds, timeout=config.round_timeout)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/server/server.py", line 106, in fit
    res_fit = self.fit_round(server_round=current_round, timeout=timeout)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/server/server.py", line 244, in fit_round
    ] = self.strategy.aggregate_fit(server_round, results, failures)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/src/ADMM_strategy.py", line 28, in aggregate_fit
    y_local = json.loads(res.metrics["Y"].decode("utf-8"))
KeyError: 'Y'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_server.py", line 1212, in _serve
    if not _process_event_and_continue(state, event):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_server.py", line 1172, in _process_event_and_continue
    rpc_state, rpc_future = _handle_call(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_server.py", line 1049, in _handle_call
    return _handle_with_method_handler(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_server.py", line 987, in _handle_with_method_handler
    return state, _handle_stream_stream(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_server.py", line 914, in _handle_stream_stream
    return thread_pool.submit(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
DEBUG flwr 2023-12-19 17:09:37,574 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:09:37,574 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:09:37,574 | connection.py:113 | gRPC channel closed
booting up client 4
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
DEBUG flwr 2023-12-19 17:09:37,578 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-12-19 17:09:37,586 | connection.py:113 | gRPC channel closed
DEBUG flwr 2023-12-19 17:09:37,587 | connection.py:113 | gRPC channel closed
booting up client 3
booting up client 2
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
DEBUG flwr 2023-12-19 17:09:37,589 | connection.py:113 | gRPC channel closed
booting up client 6
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
DEBUG flwr 2023-12-19 17:09:37,593 | connection.py:113 | gRPC channel closed
booting up client 7
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
DEBUG flwr 2023-12-19 17:09:37,681 | connection.py:39 | ChannelConnectivity.IDLE
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
DEBUG flwr 2023-12-19 17:09:37,690 | connection.py:39 | ChannelConnectivity.IDLE
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
DEBUG flwr 2023-12-19 17:09:37,777 | connection.py:113 | gRPC channel closed
booting up client 9
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
DEBUG flwr 2023-12-19 17:09:37,777 | connection.py:113 | gRPC channel closed
booting up client 8
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
DEBUG flwr 2023-12-19 17:09:37,781 | connection.py:113 | gRPC channel closed
booting up client 5
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
DEBUG flwr 2023-12-19 17:09:37,884 | connection.py:113 | gRPC channel closed
booting up client 1
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2023-12-19T17:09:37.573333583+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
DEBUG flwr 2023-12-19 17:09:37,893 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 46, in <module>
    raise self
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2023-12-19T17:09:37.585796218+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2023-12-19T17:09:37.585796178+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {grpc_message:"ping timeout", grpc_status:14, created_time:"2023-12-19T17:09:37.588613208+01:00"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2023-12-19T17:09:37.592675329+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2023-12-19T17:09:37.57340054+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2023-12-19T17:09:37.573476353+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2023-12-19T17:09:37.57750445+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2023-12-19T17:09:37.680952635+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2023-12-19T17:09:37.689890444+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
srun: error: gpu08: tasks 2-4,6-7: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9202566.1
slurmstepd: error: *** STEP 9202566.1 ON gpu08 CANCELLED AT 2023-12-19T17:09:38 ***
srun: error: gpu08: tasks 0-1,5,8-9: Terminated
srun: Force Terminated StepId=9202566.1
